In [2]:
import numpy as np

In [3]:
def info_array(a):
    print("Demension -",a.ndim)
    print("Shape -",a.shape)
    print("Size(Number of elements) -",a.size)
    print("Datatype _",a.dtype)

In [4]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
info_array(arr1)

Demension - 1
Shape - (12,)
Size(Number of elements) - 12
Datatype _ int32


### Numpy Notes
* arrange- to crate range of element - np.arange(start,end,step)
* linspace- to create the range of element with number of element, this will calulate step soze by its own,it will also inculde the start and end         value-  np.linespace (start,end,number_of_element)
* reshape- change the shape of array np.reshape(reo,column),while reshaping array the size of array should not change
* resize- changes the size of any array with given dimension,we can change array in any size, it is not dependent on how many nuber element present in    your array
* 

In [6]:
arr2 = np.linspace(1,2,34)
arr2

array([1.        , 1.03030303, 1.06060606, 1.09090909, 1.12121212,
       1.15151515, 1.18181818, 1.21212121, 1.24242424, 1.27272727,
       1.3030303 , 1.33333333, 1.36363636, 1.39393939, 1.42424242,
       1.45454545, 1.48484848, 1.51515152, 1.54545455, 1.57575758,
       1.60606061, 1.63636364, 1.66666667, 1.6969697 , 1.72727273,
       1.75757576, 1.78787879, 1.81818182, 1.84848485, 1.87878788,
       1.90909091, 1.93939394, 1.96969697, 2.        ])

In [7]:
arr3 = np.linspace(10,45,6)
arr3

array([10., 17., 24., 31., 38., 45.])

In [8]:
arr4 = np.linspace(1,9,3)
arr4

array([1., 5., 9.])

In [9]:
arr5 = np.linspace(1,5,125)
arr5

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        , 2.03225806, 2.06451613, 2.09677419,
       2.12903226, 2.16129032, 2.19354839, 2.22580645, 2.25806452,
       2.29032258, 2.32258065, 2.35483871, 2.38709677, 2.41935484,
       2.4516129 , 2.48387097, 2.51612903, 2.5483871 , 2.58064516,
       2.61290323, 2.64516129, 2.67741935, 2.70967742, 2.74193548,
       2.77419355, 2.80645161, 2.83870968, 2.87096774, 2.90322581,
       2.93548387, 2.96774194, 3.        , 3.03225806, 3.06451613,
       3.09677419, 3.12903226, 3.16129032, 3.19354839, 3.22580645,
       3.25806452, 3.29032258, 3.32258065, 3.35483871, 3.38709

In [10]:
info_array(arr5)

Demension - 1
Shape - (125,)
Size(Number of elements) - 125
Datatype _ float64


In [16]:
arr6 = np.linspace(1,24,24, dtype="int")
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [17]:
arr6.shape

(24,)

In [18]:
arr6.reshape(4,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

# Reshape above array with following shape - (12,2),(2,12), (8,3),(3,8),(3,4,2)

In [19]:
arr6.reshape(3,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [20]:
arr6.reshape(12,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [21]:
arr6.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [22]:
arr6.reshape(8,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [23]:
arr6.reshape(3,8)


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
arr6.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [27]:
arr6.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [28]:
arr6.reshape(24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [29]:
arr6.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr6.reshape(1,-1).shape

(1, 24)

In [32]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [40]:
arr6.ravel("C")# c programming

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
arr6.ravel("F") # FORTRON 77 programing

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
arr6.resize(8,3)

In [43]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [45]:
arr6.resize(3,8)
arr6

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
arr6.resize(7,5)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [48]:
np.resize(arr6,(7,5)) #possible

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24,  1],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [49]:
np.resize(arr6,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])