In [2]:
print("hello Numpy")


hello Numpy


pip install numpy pandas matplotlib scikit-learn openpyxl seaborn 

In [3]:
import numpy as np

### Numpy
* Numericla Python- Sajorely works array called ndarray
* ndarray -  n dimensional array
* Statical library comes with many statistical functions and packages
* Numpy is the fast processed librabry built with C compiler
* Every numpy array is already compiled with C so that it will take less time to execute
* why numpy is developed where python already hhas list data structure?
* numpyy array caluculation is done elementwise
* default datatype in numpy is float
* it can store string, integer also  l

In [8]:
ls = [1,2,3,4,5,6,7,8]

In [9]:
ls

[1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
ls[4]

5

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
arr[4]

5

In [16]:
ls2 = [1,2,3],[4,5,6],[7,8,9]
ls2

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [20]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 #Matrix 3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2.ndim  # ndim is the number of dimension

2

In [23]:
ls*2

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [26]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2.shape  #shape  shows number of rows and columns

(3, 3)

In [31]:
arr2.size  #size returns number if element is array

9

In [33]:
arr3 = np.arange(5,67,8)
arr3

array([ 5, 13, 21, 29, 37, 45, 53, 61])

In [34]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [36]:
arr4 = np.arange(1,65)

In [37]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [38]:
arr4.ndim

1

In [39]:
arr4.shape

(64,)

In [40]:
arr4.size

64

In [41]:
np.array([[1,2,3],[4,5,6]]).shape

(2, 3)

In [42]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [44]:
arr4.reshape(2,32) # reshape use to change dimension of array, while doing it we cannot change size of an array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])